services:
- type: web
  name: eatlyze-backend
  env: python
  plan: free
  buildCommand: pip install --upgrade pip && pip install --no-cache-dir -r backend/requirements.txt
  startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
  autoDeploy: true
